### ISSUE TITLE
quarto run help invalid command

### ISSUE THREAD

**Issue by dpastoor** [quarto-dev/quarto-web#125]
per guidance on: https://github.com/quarto-dev/quarto-web/blob/main/docs/interactive/shiny/running.qmd#L43

but get:

![image](https://user-images.githubusercontent.com/3196313/163409852-7bec2a25-7089-4635-8be7-33cf85f39b7e.png)

> devins-mbp-2:environments.rstudio.com devin$ quarto --version
0.9.120

**Comment by cderv** [comment]
It seems like `quarto run` is not a recognize command 
````
❯ quarto help run
ERROR: Unknown command "run". Did you mean command "render"?

Error: Unknown command "run". Did you mean command "render"?
    at HelpCommand.fn (https://deno.land/x/cliffy@v0.19.3/command/help/mod.ts:20:17)
    at HelpCommand.execute (https://deno.land/x/cliffy@v0.19.3/command/command.ts:997:18)
    at HelpCommand.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:918:27)
    at async Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:870:16)
    at async quarto (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:93:3)
    at async file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:113:5
````

Not listed in available command 🤔 
````
❯ quarto help

  Usage:   quarto
  Version: 99.9.9

  Description:

    Quarto CLI

  Options:

    -h, --help     - Show this help.
    -V, --version  - Show the version number for this program.

  Commands:

    render          [input] [args...]  - Render input file(s) to various document types.
    serve           [input]            - Serve an interactive document.
    create-project  [dir]              - Create a project for rendering multiple documents
    preview         [file] [args...]   - Render and preview a Quarto document or website project. Automatically reloads the browser when
    convert         [input]            - Convert documents to alternate representations.
    capabilities                       - Query for current capabilities (output formats, engines, kernels etc.)
    check           [target]           - Check and verify correct functioning of Quarto installation and computation engines.
    inspect         [path]             - Inspect a Quarto project or input path. Inspecting a project returns its config and engines.
    tools           [command] [tool]   - Manage the installation, update, and uninstallation of useful tools.
    help            [command]          - Show this help or the help of a sub-command.
````

**Comment by jjallaire** [comment]
Yes the `run` and `pandoc` commands are handled prior to our CLI library getting control so they don't show up in help (I don't know if there is anything we can do to remedy this)

**Comment by cderv** [comment]
That explains it then. Thanks. 

The other part of the above issue is that all the shiny part in the doc needs an update it seems.
https://quarto.org/docs/interactive/shiny/running.html#command-line

Do you want a PR ?

**Comment by jjallaire** [comment]
I just made the fix to the docs, thanks!
